Change to Jarred-Sumner/bun

diff --git a/bin/install b/bin/install
--- a/bin/install
+++ b/bin/install
@@ -18,64 +18,87 @@ fail() {
   exit 1
 }
 
-install_deno() {
+# Reset
+Color_Off=''
+
+# Regular Colors
+Red=''
+Green=''
+
+# Bold
+BWhite=''
+BGreen=''
+
+Dim='' # White
+
+if test -t 1; then
+    # Reset
+    Color_Off='\033[0m' # Text Reset
+
+    # Regular Colors
+    Red='\033[0;31m'   # Red
+    Green='\033[0;32m' # Green
+    White='\033[0;37m' # White
+
+    Dim='\033[0;2m' # White
+
+    # Bold
+    BGreen='\033[1;32m' # Green
+    BWhite='\033[1;37m' # White
+fi
+
+install_bun() {
   local install_type=$1
   local version=$2
   local install_path=$3
 
-  if [ "$install_type" != "version" ]; then
-    fail "asdf-deno supports release installs only"
+  if ! command -v unzip >/dev/null; then
+    echo -e "${Red}error${Color_Off}: unzip is required to install Bun (see: https://github.com/Jarred-Sumner/bun#unzip-is-required)." 1>&2
+    exit 1
   fi
 
-  local platform
-  local architecture
-  local archive_format
+  if [ "$install_type" != "version" ]; then
+    fail "asdf-bun supports release installs only"
+  fi
+
+  local target
+
+  if [ "$OS" = "Windows_NT" ]; then
+    echo "error: Please install Bun using Windows Subsystem for Linux."
+    exit 1
+  else
+      case $(uname -sm) in
+      "Darwin x86_64") target="darwin-x64" ;;
+      "Darwin arm64") target="darwin-aarch64" ;;
+      *) target="linux-x64" ;;
+      esac
+  fi
+
+  if [ "$target" = "darwin-x64" ]; then
+    # Is it rosetta
+    sysctl sysctl.proc_translated >/dev/null 2>&1
+    if [ $? -eq 0 ]; then
+        target="darwin-aarch64"
+        echo -e "$Dim Your shell is running in Rosetta 2. Downloading Bun for $target instead. $Color_Off"
+    fi
+  fi
+
   local uncompress_command
   local archive_file
 
-  if [[ $version > "0.35.0" ]]; then
-    case "$OSTYPE" in
-      darwin*) platform="apple-darwin" ;;
-      linux*) platform="unknown-linux-gnu" ;;
-      *) fail "Unsupported platform" ;;
-    esac
+  archive_file="deno-${target}.zip"
+  uncompress_command="unzip -d ${install_path}/bin"
 
-    case "$(uname -m)" in
-      x86_64) architecture="x86_64" ;;
-      arm64) architecture="aarch64" ;;
-      *) fail "Unsupported architecture" ;;
-    esac
+  local download_url="https://github.com/Jarred-Sumner/bun/releases/download/v${version}/${archive_file}"
+  local source_path="${install_path}/bin/bun.${archive_format}"
 
-    archive_format="zip"
-    archive_file="deno-${architecture}-${platform}.${archive_format}"
-    uncompress_command="unzip -d ${install_path}/bin"
-  else
-    case "$OSTYPE" in
-      darwin*) platform="osx" ;;
-      linux*) platform="linux" ;;
-      *) fail "Unsupported platform" ;;
-    esac
-
-    case "$(uname -m)" in
-      x86_64) architecture="x64" ;;
-      *) fail "Unsupported architecture" ;;
-    esac
-
-    archive_format="gz"
-    archive_file="deno_${platform}_${architecture}.${archive_format}"
-    uncompress_command="gunzip"
-  fi
-
-  local download_url="https://github.com/denoland/deno/releases/download/v${version}/${archive_file}"
-  local source_path="${install_path}/bin/deno.${archive_format}"
-
-  echo "* Downloading and installing deno..."
+  echo "* Downloading and installing bun..."
   curl --fail --silent --location --create-dirs --output "$source_path" "$download_url"
   $uncompress_command "$source_path"
-  chmod +x "${install_path}/bin/deno"
-  mkdir "${install_path}/.deno"
+  chmod +x "${install_path}/bin/bun"
+  mkdir "${install_path}/.bun"
   rm "$source_path"
   echo "The installation was successful!"
 }
 
-install_deno "$ASDF_INSTALL_TYPE" "$ASDF_INSTALL_VERSION" "$ASDF_INSTALL_PATH"
+install_bun "$ASDF_INSTALL_TYPE" "$ASDF_INSTALL_VERSION" "$ASDF_INSTALL_PATH"
